### ISSUE TITLE
VOC Dependency Bump

### ISSUE THREAD

**Issue by dcatoday** [SheetJS/frac#2]
Hi, 

The VOC library was updated to version 1.1.0 in order to fix a security vulnerability.  The package.json in this library is currently pointing to 1.0.x with the ~.  Is it possible to update this with the ^ so that it can pull in the latest version of the VOC library.

Thanks

**Comment by SheetJSDev** [comment]
`voc` was switched to a dev dependency in 1.1.2, we're working through the dependency tree to update everything.
